name: CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Lint with black, isort and flake8
      run: |
        black star_of_africa tests --check --verbose
        isort star_of_africa tests --check-only
        flake8 star_of_africa tests --count --max-complexity=10  --max-line-length=88 --show-source --statistics
    - name: Test with pytest
      run: |
        pytest --cov=star_of_africa --capture=no --verbose tests --cov-report xml:coverage/coverage.xml --cov-report term-missing
